### ISSUE TITLE
Default Yaml configuration leads to incorrect Yaml

### ISSUE THREAD

**Issue by fanf** [zio/zio-json#1003]
The current configuration options for SnakeYaml layer leads to it outputing badly formatted yaml like: 

```
id: foo
version: 42
params:
  -
  id: p1
  mandatory: true
```

It seems that `setIndentWithIndicator(true)` option is missing (and not exposed). 

See https://gist.github.com/fanf/445e9228cd62bb786960ce2242c1020c for more details.
